version: '3.5'
services:
    web:
        build: .
        command: [sh, -c, "pip install -r requirements.txt && gunicorn app:app"]
        ports:
            - "5000:5000"
        volumes:
            - .:/code